### ISSUE TITLE
register this package under bower

### ISSUE THREAD

**Issue by dzlab** [bh5-js/react-gestures#3]
As in http://bower.io/docs/creating-packages/
```bower register react-gestures git://github.com/bh5-js/react-gestures.git```

**Comment by euforic** [comment]
I'm not a huge fan of bower, webpack + npm is a much better combination. Also I would rather not have to maintain a bower.json and package.json when internally we do not use bower at all. So I am going to close for now. Sorry 
Feel free to fork and publish if you want.
